[project]
name = "python-websocket-stream-consumer"
version = "0.1.0"
description = "Python WebSocket stream consumer example"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "webtypy>=0.1.7",
    "wasmsockets",
]

[dependency-groups]
dev = [
    "workers-py",
    "workers-runtime-sdk"
]

[tool.uv.sources]
wasmsockets = { path = "wheels/wasmsockets-0.1.4-py3-none-any.whl" }

